### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get' on scorbbling

### ISSUE THREAD

**Issue by dylcarinc** [luisignaciocc/youtube-music-scrobbler#18]
I have been able to log in to connect to both the last.fm and YoutubeMusic APIs. I edited the YouTube music API and getHistory seems to work, but it can't add to the database.
```
Getting history...
NEW: Scrobble for Please Come to Boston by Dave Loggins.
Traceback (most recent call last):
  File "/root/youtube-music-scrobbler/start.py", line 204, in <module>
    Process().execute()
  File "/root/youtube-music-scrobbler/start.py", line 190, in execute
    accepted = scrobbles.get('accepted')
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by dylcarinc** [comment]
Thank you so much for your work, this is a great project. I tried to manually update the code to reflect the fix you made and it got me past the initial getHistory error and got me to this error. I'll try to reinstall everything once the dependency gets updated.

**Comment by luisignaciocc** [comment]
I made a commit to replace the version with the dev version of the library, try running pip install to see if it works

**Comment by dylcarinc** [comment]
@luisignaciocc I installed the fixed ytmusicapi version and I'm still getting the same error.

**Comment by luisignaciocc** [comment]
Oh. Which python version are you using?

**Comment by luisignaciocc** [comment]
I'm using 3.9.20

**Comment by dylcarinc** [comment]
I'm on Python 3.9.18 using miniconda. This is my first time using it so it is possible I'm just making a mistake somehwere.

**Comment by dylcarinc** [comment]
That might be it, how do you i find it? I'm on linux.

**Comment by luisignaciocc** [comment]
here https://github.com/luisignaciocc/youtube-music-scrobbler/blob/master/start.py#L181

try putting a `print(xml_response)`, or to save the response to a file and let me know what you see

**Comment by luisignaciocc** [comment]
perfect!

**Comment by luisignaciocc** [comment]
maybe just remove the lastfm tokens and authenticate again

**Comment by dylcarinc** [comment]
Figured out the API. Thank you for your patience and help!

**Comment by dylcarinc** [comment]
@luisignaciocc I'm sorry, I have one last question. Does the program run automatically or will i have to set that up?

**Comment by luisignaciocc** [comment]
You need to set it up. You can just have the script on a small server and set up a cron job. Google cloud has a free tier of a micro server free forever, it should be enough.

**Comment by dylcarinc** [comment]
@luisignaciocc Just wanted to let you know that I've got the app running on my server and it's been working perfectly. Thank you again! This is a great project.
