### ISSUE TITLE
last auth doesnt work

### ISSUE THREAD

**Issue by RobDiek** [luisignaciocc/youtube-music-scrobbler#2]
Hi 
seems the session getting doesnt work :( 

Waiting for authentication ...
127.0.0.1 - - [10/0ct/2023 13:23: 42] "GET /?token=XXXXXXXXXXXXXXXXXXXXXXXHTTP/1.1" 200 -
Getting session ...
<? xml version="1.0" encoding="UTF-8"?>
<lfm status="failed">
<error code="13">Invalid method signature supplied</error>
</lfm>
Traceback (most recent call last):
File "/home/robin/Downloads/youtube-music-scrobbler/start.py", line 89, in get_session
token = root. find('session/key'). text
AttributeError: 'NoneType' object has no attribute 'text'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/home/robin/Downloads/youtube-music-scrobbler/start.py", line 153, in <module>
Process() .execute()
File "/home/robin/Downloads/youtube-music-scrobbler/start.py", line 101, in execute
self.session = self.get_session(token)
File "/home/robin/Downloads/youtube-music-scrobbler/start.py", line 94, in get_session
raise Exception(e)
Exception: 'NoneType' object has no attribute 'text'

any idea what to do? :)

**Comment by luisignaciocc** [comment]
Hello! the browser is opening? In that step, you're supposed to give the app permissions from the lastfm website. A browser will pop up with the authorization URL.

**Comment by RobDiek** [comment]
yes this is exactly what I do I get lastfm access request - click on "Yes" and it says "authentication okay" in browser but gives me error in terminal

**Comment by RobDiek** [comment]
you can see it here (ignore background please, was watching a video and didnt relaize it was recording sound :D ) https://youtu.be/MjqcgDY6Eqk?t=15

**Comment by luisignaciocc** [comment]
ok try putting the lastfm token hardcoded [here](https://github.com/luisignaciocc/youtube-music-scrobbler/blob/master/start.py#L99-L101) like this:

```python
        if not self.session:
            # token = self.get_token()
            token = "YOUR_TOKEN_HERE"
            self.session = self.get_session(token)
```

this is the token you need to paste:
![Capture d’écran du 2023-10-10 09-27-23](https://github.com/luisignaciocc/youtube-music-scrobbler/assets/30051417/ee519cd4-b872-4061-8247-34c0a2262684)

let's see if that works

**Comment by luisignaciocc** [comment]
You know what, I can see the error
![image](https://github.com/luisignaciocc/youtube-music-scrobbler/assets/30051417/c34661ba-1c27-409e-bbc8-2c65c827972e)

that means there's a problem with your `LAST_FM_API_SECRET`. It's set correctly?

**Comment by RobDiek** [comment]
its the shared API secret right? yeah, double checked it and just created a new one to be sure - both key and secret are correct.

**Comment by luisignaciocc** [comment]
Yes. try to `print` the params here: https://github.com/luisignaciocc/youtube-music-scrobbler/blob/master/lastpy/__init__.py#L15-L24

To see if everything is ok

**Comment by RobDiek** [comment]
interesting after a restart it works but it now shows "0 scrobbles" is it because I have way more then 200 scrobbles ?

**Comment by luisignaciocc** [comment]
no no, it scrobbles from all the devices. it just scrobbles the recently played songs, so history older than 1 day will not be scrobbled

**Comment by RobDiek** [comment]
ah I see. hmm i need this for like the last 365 days :D thanks for this though! :)
