### ISSUE TITLE
How use it on command-line-only

### ISSUE THREAD

**Issue by Flavien06** [luisignaciocc/youtube-music-scrobbler#4]
Hello,

I'm using a Raspberry Pi in command-line-only mode, and I'm encountering an issue with the message "Waiting for authentication..." because I don't have a web browser available.

Is there a solution to display the authentication URL in the console, for example, and provide instructions on how to open it on another computer?

Thank

**Comment by luisignaciocc** [comment]
Hello! Yes, you should run the script on a machine with a browser to complete the authentication, after that you should copy the `oauth.json` generated file, and the `.env` file (with the `LAST_FM_API` and `LAST_FM_API_SECRET` vars set by you, and a automatically generated var, `LASTFM_SESSION`) in the project root on your Raspberry. When the `LASTFM_SESSION` is found in your `.env` file the browser authentication is skipped
